<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Your Website</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0; padding: 0;
      background: #f5f5f5;
      color: #333;
    }

    header {
      background: #0077cc;
      color: white;
      padding: 1rem;
      text-align: center;
    }

    nav a {
      color: white;
      margin: 0 1rem;
      text-decoration: none;
    }

    nav a:hover {
      text-decoration: underline;
    }

    main {
      padding: 2rem;
      max-width: 900px;
      margin: auto;
      background: white;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    footer {
      text-align: center;
      padding: 1rem;
      background: #222;
      color: white;
      margin-top: 2rem;
    }

    button {
      background-color: #0077cc;
      color: white;
      border: none;
      padding: 10px 20px;
      font-size: 1rem;
      cursor: pointer;
      margin-top: 1rem;
      border-radius: 5px;
    }

    button:hover {
      background-color: #005fa3;
    }
  </style>
</head>
<body>
  <header>
    <h1>Welcome to Your Website</h1>
    <nav>
      <a href="#">Home</a>
      <a href="#">About</a>
      <a href="#">Services</a>
      <a href="#">Contact</a>
    </nav>
  </header>

  <main>
    <section>
      <h2>About Us</h2>
      <p>This is a great place to tell visitors about yourself or your business.</p>
      <button id="alertBtn">Click me!</button>
    </section>
  </main>

  <footer>
    <p>© 2025 Your Name. All rights reserved.</p>
  </footer>

  <script>
    document.getElementById('alertBtn').addEventListener('click', () => {
      alert('Hello! Thanks for visiting.');
    });
  </script>
</body>
</html>