<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Simple Website</title>
    <link rel="stylesheet" href="styles.css"> <!-- Links the CSS file -->
</head>
<body>
    <header>
        <h1>Welcome to My Website</h1>
        <nav>
            <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#gallery">Gallery</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="about">
            <h2>About Me</h2>
            <p>Hello! This is a simple website built with HTML, CSS, and JavaScript.</p>
        </section>
        <section id="gallery">
            <h2>Gallery</h2>
            <div class="gallery">
                <img src="https://via.placeholder.com/150" alt="Sample Image 1">
                <img src="https://via.placeholder.com/150" alt="Sample Image 2">
                <img src="https://via.placeholder.com/150" alt="Sample Image 3">
            </div>
        </section>
        <section id="contact">
            <h2>Contact</h2>
            <form id="contact-form">
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>
                <label for="message">Message:</label>
                <textarea id="message" name="message" required></textarea>
                <button type="submit">Send</button>
            </form>
        </section>
    </main>
    <footer>
        <p>&copy; 2025 My Website</p>
    </footer>
    <script src="script.js"></script> <!-- Links the JavaScript file -->
</body>
</html>