// Wait for the DOM to load
document.addEventListener("DOMContentLoaded", () => {
    const form = document.getElementById("contact-form");

    // Add event listener for form submission
    form.addEventListener("submit", (event) => {
        event.preventDefault(); // Prevent form from refreshing the page
        const name = document.getElementById("name").value;
        const message = document.getElementById("message").value;

        // Simple alert to show the submitted data
        alert(`Thank you, ${name}! Your message: "${message}" has been received.`);
    });
});